alias pk='ping krishna'
alias n='vi ~/Sites/newscheduler/app/notes'
alias db='mv ~/Downloads/database.sql ~/Sites/newscheduler/app/config/sql/'
alias pushimp='scp import.php shantam@krishna:/var/www/html/'
alias cpimp='cp import.php ../../'
alias bs='vi config/bootstrap.php'
